# Generated by Django 4.1.2 on 2022-11-14 01:37

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
    ]
