# Generated by Django 4.1.2 on 2022-11-14 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_card_billing_addr_alter_card_card_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='card_info',
        ),
        migrations.AddField(
            model_name='card',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
