# Generated by Django 4.1.2 on 2022-11-14 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_avatar_alter_customuser_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='recurrences',
        ),
        migrations.AlterField(
            model_name='card',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Card holder'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pmt_option',
            field=models.CharField(choices=[('M', 'Monthly Plan $14.99 per month'), ('Y', 'Yearly Plan $149.99 per year')], max_length=30, verbose_name='Payment Plan'),
        ),
    ]
