# Generated by Django 4.1.2 on 2022-11-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_card_recurrences_alter_card_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_num',
            field=models.CharField(max_length=16, verbose_name='Card Number'),
        ),
    ]
