# Generated by Django 4.1.2 on 2022-11-15 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_card_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='billing_addr',
            field=models.CharField(max_length=100, verbose_name='Billing address'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_num',
            field=models.CharField(max_length=16, verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='card',
            name='pmt_option',
            field=models.CharField(choices=[('M', 'Monthly Plan $14.99 per month'), ('Y', 'Yearly Plan $149.99 per year'), ('N', 'None')], default='N', max_length=30, verbose_name='Payment plan'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Payment amount')),
                ('pmt_date', models.DateTimeField(auto_now_add=True, verbose_name='Payment date')),
                ('success', models.BooleanField(default=False)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pmt_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.card')),
            ],
        ),
    ]
