# Generated by Django 4.1.2 on 2022-11-15 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_card_billing_addr_alter_card_card_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pmt_date',
            field=models.DateTimeField(verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pmt_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.card', verbose_name='Payment method'),
        ),
    ]
