# Generated by Django 4.1.2 on 2022-11-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_card_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pmt_method',
            field=models.CharField(max_length=16, null=True, verbose_name='Payment method'),
        ),
    ]
