# Generated by Django 4.1.2 on 2022-11-18 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_payment_pmt_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Card holder'),
        ),
    ]
