# Generated by Django 4.1.2 on 2022-11-19 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_card_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Membership price')),
                ('type', models.CharField(choices=[('M', 'Monthly subscription'), ('Y', 'Yearly subscription')], max_length=1, verbose_name='Billing cycle')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='sub_edate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pmt_option',
            field=models.CharField(choices=[('M', 'Monthly Plan'), ('Y', 'Yearly Plan'), ('N', 'Inactive / Cancel plan')], default='N', max_length=1, verbose_name='Payment plan'),
        ),
    ]
