# Generated by Django 4.1.3 on 2022-11-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('geolocation', models.TextField(max_length=500)),
                ('postalcode', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=100)),
                ('amenitiestype', models.TextField(max_length=500)),
                ('amenitiesquantity', models.TextField(max_length=500)),
                ('imagelist', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
