# Generated by Django 4.1.3 on 2022-11-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Studio Name')),
                ('address', models.TextField(help_text='Please seperate street name, city, and province by comma', max_length=500, verbose_name='Studio Address')),
                ('geolocation', models.TextField(help_text='Please seperate longitude and latitude by comma. Eg. 121.1111, 90.28', max_length=500, verbose_name='longitude, latitude')),
                ('postalcode', models.CharField(help_text='Eg. M5S 1C6', max_length=7, verbose_name='Postal Code')),
                ('phonenumber', models.CharField(help_text='Eg. 6471231230', max_length=10, verbose_name='Phone Number')),
                ('amenitiestype', models.TextField(max_length=500, verbose_name='Amenities Type')),
                ('amenitiesquantity', models.TextField(help_text="Please correspond to each amenity's type. And seperate each integer by comma.", max_length=500, verbose_name='Amenities Quantity')),
                ('imagelist', models.TextField(blank=True, help_text='Please seperate each image by comma', null=True, verbose_name='Link of Images')),
            ],
        ),
    ]
