# Generated by Django 4.1.3 on 2022-12-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='geolocation',
            field=models.TextField(help_text='Please seperate longitude and latitude by comma. Eg. 55.854261,-4.234524', max_length=500, verbose_name='longitude, latitude'),
        ),
    ]
