# Generated by Django 4.1.3 on 2022-11-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_alter_studio_address_alter_studio_amenitiesquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Studio Name'),
        ),
    ]
