# Generated by Django 4.1.3 on 2022-11-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('end_time', models.DateTimeField(blank=True, help_text='You can leave this field blank and it will be calculated automatically')),
                ('course_end_time', models.DateTimeField()),
                ('studio', models.CharField(default='studio', max_length=100)),
                ('is_cancelled', models.BooleanField(blank=True, default=False)),
                ('space_availability', models.PositiveIntegerField(blank=True, default=models.PositiveIntegerField())),
            ],
        ),
    ]
