# Generated by Django 4.1.3 on 2022-11-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('coach', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('studio', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='class',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='start_date',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='class',
            name='studio',
            field=models.CharField(default='studio', max_length=100),
        ),
    ]
