# Generated by Django 4.1.3 on 2022-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_userenrolledclass_remove_class_course_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_time',
            field=models.DateTimeField(help_text='Every instance of this class ends before end time.'),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_time',
            field=models.DateTimeField(help_text='This is the start time of the first instance of this class.'),
        ),
    ]
