# Generated by Django 4.1.3 on 2022-11-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classinstance_rename_end_date_class_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinstance',
            name='space_availability',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
