# Generated by Django 4.1.3 on 2022-11-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_classinstance_space_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinstance',
            name='is_cancelled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
