# Generated by Django 4.1.3 on 2022-11-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classinstance_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEnrolledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('class_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='classinstance',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
